---
title: "Report"
author: "Nadine T. & Anastasia K."
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r libraries}
library(readxl)
library(dplyr)
library(tibble)
library(psych)
library(tidyr)
library(flextable)
library(tibble)

Sys.setlocale("LC_CTYPE", "russian")
```

```{r upload}
Data_05 <- read_xlsx ("Data/Raw/2005.xlsx")
```


```{r structure}
names(Data_05) <- c("case","gndr","live","age","gest","LB","WB","brn","hrt","lung","liver","spln","kid","thym","adr","panc","plac","mac","CM","MP","IUGR","HC","CC")

Data_05.varlab <- c("case" = "№ протокола",
                    "gndr" = "пол;
                    m - мужчина;
                    f - женщина",
                    "live" = "мёртвый/живой;
                    still - мёртв",
                    "age" = "возраст, сут",
                    "gest" = "гестация, нед",
                    "LB" = "длина тела (Length Body), см ",
                    "WB" = "масса тела (Weigth Body), гр",
                    "brn" = "мозг, гр",
                    "hrt" = "сердце, гр",
                    "lung" = "лёгкие, гр",
                    "liver" = "печень, гр",
                    "spln" = "селезёнка, гр",
                    "kid" = "почки, гр",
                    "thym" = "тимус, гр",
                    "adr" = "надпочечники, гр",
                    "panc" = "поджелудочная железа, гр",
                    "plac" = "плацента",
                    "mac" = "мацерация;
                    0 - отсутствие;
                    1 - наличие",
                    "CM" = "врожденные пороки развития (Congenital Malformation);
                    inf - инфекции;
                    limf - лимфангиоэктазии;
                    mss - костно-мышечная система (musculoskeletal system);
                    diaf - диафрагмальная грыжа;
                    gshi - гастрошизис;
                    cvs - сердечнососудистая система (cardiovascular system);
                    ehs - отёчно-геморрагический синдром (edematous hemorrhagic syndrome);
                    ds - дистресс-синдром (????);
                    mcm - множественные пороки развития (multiple congenital malformations);
                    git - желудочно-кишечный тракт (gastrointestinal tract);
                    - ОГС (???);
                    Edv - синдром Эдвардса;
                    Down - синдром Дауна;
                    asp - аспирация;
                    omph - омфалоцеле;
                    muc - мукополисахаридозы (МПС);
                    diabph - диабетическая фетопатия;
                    med - медицинские показания;
                    cns - центральная нервная система (central nervous system);
                    AK - аномалия Арнольда-Киари;
                    pneu - пневмония;
                    yes - присутствие ВПР;
                    no - отсутствие ВПР.",
                    "MP" = "многоплодная беременность;
                    0 - отсутствие;
                    1 - наличие",
                    "IUGR" = "синдром задержки развития плода (Intrauterine Growth Restriction);
                    0 - отсутствие;
                    1 - СЗРП;
                    2 - СРПП;
                    3 - ЗВУР;
                    4 - СЗРП 3.",
                    "НС" = "окружность головы (Head Circumference), см",
                    "CC" = "окружность груди (Chest Circumference), см")
```

```{r}
Data_05 <- transform(Data_05,
                     gndr = factor(gndr,
                                   levels = c(1,2),
                                   labels = c("m","f")),
                     live = factor(live,
                                   levels = c(0,1),
                                   labels = c("live","still")),
                     mac = factor(mac,
                                  levels = c(0,1),
                                  labels = c("no","yes")),
                     MP = factor(MP,
                                 levels = c(0,1),
                                 labels = c("no","yes")),
                     IUGR = factor(IUGR,
                                   levels = c(0,1,2,3,4),
                                   labels = c("no","IUGR","???","???","IUGR 3")))
```


